services:
  db:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  proxy:
    image: ghcr.io/sagernet/sing-box:latest
    container_name: proxy-agent
    restart: always
    dns:
      - 8.8.8.8
      - 1.1.1.1
    ports:
      - "5678:5678"
    volumes:
      - ./sing-box-config.example.json:/etc/sing-box/config.json:ro
    command: run -c /etc/sing-box/config.json

  n8n:
    image: n8nio/n8n:2.9.2
    network_mode: "service:proxy"
    restart: always
    environment:
      TZ: ${TZ}
      GENERIC_TIMEZONE: ${GENERIC_TIMEZONE}
      N8N_PROXY_HOPS: ${N8N_PROXY_HOPS}
      N8N_ENCRYPTION_KEY: ${N8N_ENCRYPTION_KEY}
      N8N_SECURE_COOKIE: ${N8N_SECURE_COOKIE}
      N8N_EDITOR_BASE_URL: ${N8N_EDITOR_BASE_URL}
      WEBHOOK_URL: ${WEBHOOK_URL}
      DB_TYPE: postgresdb
      DB_POSTGRESDB_HOST: ${DB_POSTGRESDB_HOST}
      DB_POSTGRESDB_PORT: ${DB_POSTGRESDB_PORT}
      DB_POSTGRESDB_DATABASE: ${DB_POSTGRESDB_DATABASE}
      DB_POSTGRESDB_USER: ${DB_POSTGRESDB_USER}
      DB_POSTGRESDB_PASSWORD: ${DB_POSTGRESDB_PASSWORD}
      HTTP_PROXY: ${HTTP_PROXY}
      HTTPS_PROXY: ${HTTPS_PROXY}
      GLOBAL_AGENT_HTTP_PROXY: ${GLOBAL_AGENT_HTTP_PROXY}
      GLOBAL_AGENT_HTTPS_PROXY: ${GLOBAL_AGENT_HTTPS_PROXY}
      NO_PROXY: ${NO_PROXY}
      GLOBAL_AGENT_NO_PROXY: ${GLOBAL_AGENT_NO_PROXY}
      N8N_DIAGNOSTICS_ENABLED: "false"
      N8N_VERSION_NOTIFICATIONS_ENABLED: "false"
      N8N_TELEMETRY_ENABLED: "false"
    depends_on:
      - db
      - proxy

  duckdns:
    image: lscr.io/linuxserver/duckdns:latest
    container_name: duckdns
    network_mode: host
    restart: unless-stopped
    environment:
      PUID: "1000"
      PGID: "1000"
      TZ: ${TZ}
      SUBDOMAINS: ${DUCKDNS_SUBDOMAINS}
      TOKEN: ${DUCKDNS_TOKEN}
      LOG_FILE: "false"

  nginx-proxy:
    image: jc21/nginx-proxy-manager:latest
    restart: always
    ports:
      - "80:80"
      - "81:81"
      - "443:443"
    volumes:
      - npm_data:/data
      - npm_letsencrypt:/etc/letsencrypt

volumes:
  postgres_data:
  npm_data:
  npm_letsencrypt:

